version: '3.8'
services:
  php-apache-environment:
    container_name: php8.1-a-srv
    build: ./php
    depends_on:
      - base_mysql
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "80:80"